name: House
main: EnterTainerSK\House
version: 1.0.0
api: [3.0.0, 4.0.0]

author: EnterTainerSK
description:  Custom buildings plugin

commands:
    house:
        usage: /house
        description: Give all houses
        default: op
